
let data =
{
  pl_min: 0,
  liq_min: 0,
  patrim_min: 0,
  divbruta_max: "",
  pl_max: "",
  pvp_min: "",
  pvp_max: "",
  psr_min: "",
  psr_max: "",
  divy_min: "",
  divy_max: "",
  pativos_min: "",
  pativos_max: "",
  pcapgiro_min: "",
  pcapgiro_max: "",
  pebit_min: "",
  pebit_max: "",
  fgrah_min: "",
  fgrah_max: "",
  firma_ebit_min: "",
  firma_ebit_max: "",
  firma_ebitda_min: "",
  firma_ebitda_max: "",
  margemebit_min: "",
  margemebit_max: "",
  margemliq_min: "",
  margemliq_max: "",
  liqcorr_min: "",
  liqcorr_max: "",
  roic_min: "",
  roic_max: "",
  roe_min: "",
  roe_max: "",
  liq_max: "",
  patrim_max: "",
  divbruta_min: "",
  tx_cresc_rec_min: "",
  tx_cresc_rec_max: "",
  setor: "",
  negociada: "ON",
  ordem: "1",
  x: "19",
  y: "24",
}


module.exports = { data } 